;;; pai-mcp-sources-test.el --- Declarative MCP source tests -*- lexical-binding: t; -*-
;;; Code:
(require 'ert)
(require 'cl-lib)
(require 'pai-mcp-sources)
(require 'pai-mcp-client)

(defmacro pai-mcp-sources-test--isolated (&rest body)
  "Run BODY with an isolated HOME, project, Pi state, and runtime registry."
  (declare (indent 0))
  `(let* ((home (make-temp-file "pai-mcp-sources-" t))
          (dir (expand-file-name "work/project" home))
          (pai-directory (expand-file-name ".pi/agent" home))
          (process-environment (cons (concat "HOME=" home) process-environment))
          (pai-mcp--runtime-servers nil) (pai-mcp--provenance nil)
          (pai-mcp-source-change-hook nil)
          (pai-mcp--servers (make-hash-table :test #'equal))
          (pai-mcp--metadata nil))
     (make-directory dir t)
     (let ((default-directory (file-name-as-directory dir)))
       (unwind-protect (progn ,@body) (delete-directory home t)))))

(defun pai-mcp-sources-test--file (file value)
  "Write VALUE as JSON to FILE, or as verbatim text when a string."
  (make-directory (file-name-directory file) t)
  (with-temp-file file (insert (if (stringp value) value (pai-json-encode value)))))

(ert-deftest pai-mcp-sources-standard-and-ancestor-precedence ()
  (pai-mcp-sources-test--isolated
    (let ((root (expand-file-name "work" home)))
      (pai-mcp-sources-test--file (expand-file-name "mcp.json" pai-directory)
                                (list :settings (list :ancestorConfigRoots (list root))
                                      :mcpServers '(:shared (:command "global" :timeout 12))))
      (pai-mcp-sources-test--file (expand-file-name ".mcp.json" root)
                                '(:mcpServers (:shared (:command "ancestor") :inherited (:command "ancestor-only"))))
      (pai-mcp-sources-test--file (expand-file-name ".mcp.json" dir)
                                '(:mcpServers (:shared (:command "project"))))
      (pai-mcp-sources-test--file (expand-file-name ".pi/mcp.json" dir)
                                '(:mcpServers (:shared (:disabled t))))
      (let ((config (pai-mcp-load-config dir)))
        (should (equal (plist-get (cdr (assoc "shared" config)) :command) "project"))
        (should (eq (plist-get (cdr (assoc "shared" config)) :disabled) t))
        (should (= (plist-get (cdr (assoc "shared" config)) :timeout) 12))
        (should (assoc "inherited" config))
        (should (equal (plist-get (pai-mcp-server-provenance "inherited" dir) :path) (expand-file-name ".mcp.json" root)))))))

(ert-deftest pai-mcp-sources-project-cannot-expand-ancestor-trust ()
  (pai-mcp-sources-test--isolated
    (pai-mcp-sources-test--file (expand-file-name ".mcp.json" (file-name-directory dir)) '(:mcpServers (:untrusted (:command "never"))))
    (pai-mcp-sources-test--file (expand-file-name ".mcp.json" dir) (list :settings (list :ancestorConfigRoots (list home))))
    (should-not (assoc "untrusted" (pai-mcp-load-config dir)))))

(ert-deftest pai-mcp-sources-nearest-root-and-symlink-boundary ()
  (pai-mcp-sources-test--isolated
    (let ((root (expand-file-name "work" home)))
      (pai-mcp-sources-test--file (expand-file-name ".mcp.json" home) '(:mcpServers (:too-far (:command "no"))))
      (pai-mcp-sources-test--file (expand-file-name "mcp.json" pai-directory)
                                (list :settings (list :ancestorConfigRoots (list home root)) :mcpServers '(:global (:command "g"))))
      (make-symbolic-link (expand-file-name "mcp.json" pai-directory) (expand-file-name ".mcp.json" root))
      (should-not (assoc "too-far" (pai-mcp-load-config dir)))
      (should-not (member (expand-file-name ".mcp.json" root) (pai-mcp--config-files dir))))))

(ert-deftest pai-mcp-sources-every-host-format-and-explicit-import-order ()
  (pai-mcp-sources-test--isolated
    (dolist (kind pai-mcp--host-kinds)
      (let ((file (car (pai-mcp--host-paths kind dir))))
        (pai-mcp-sources-test--file
         file (pcase kind
                ("codex" "[mcp_servers.codex]\ncommand = 'codex-tool'\n")
                ("opencode" '(:mcp (:opencode (:type "local" :command ("open-tool" "--mcp")))))
                (_ (list :mcpServers (list (intern (concat ":" kind)) (list :command kind) :shared (list :command kind))))))))
    (should-not (pai-mcp-load-config dir))
    (should (= 7 (length (pai-mcp-discover-host-configs dir))))
    (pai-mcp-add-imports pai-mcp--host-kinds dir)
    (let ((config (pai-mcp-load-config dir)))
      (dolist (kind pai-mcp--host-kinds) (should (assoc kind config)))
      (should (equal (plist-get (cdr (assoc "shared" config)) :command) "cursor"))
      (should (equal (plist-get (cdr (assoc "opencode" config)) :args) '("--mcp"))))
    (let ((json (pai-mcp--read-json-file (expand-file-name ".pi/mcp.json" dir))))
      (should-not (plist-member json :mcpServers))
      (should (equal (plist-get json :imports) pai-mcp--host-kinds)))))

(ert-deftest pai-mcp-sources-host-discovery-last-wins-below-standard ()
  (pai-mcp-sources-test--isolated
    (pai-mcp-sources-test--file (car (pai-mcp--host-paths "cursor" dir)) '(:mcpServers (:shared (:command "cursor"))))
    (pai-mcp-sources-test--file (car (pai-mcp--host-paths "windsurf" dir)) '(:mcpServers (:shared (:command "windsurf"))))
    (pai-mcp-sources-test--file (expand-file-name "mcp.json" pai-directory) '(:settings (:hostConfigDiscovery "on")))
    (should (equal (plist-get (cdr (assoc "shared" (pai-mcp-load-config dir))) :command) "windsurf"))
    (pai-mcp-sources-test--file (expand-file-name ".mcp.json" dir) '(:mcpServers (:shared (:command "project"))))
    (should (equal (plist-get (cdr (assoc "shared" (pai-mcp-load-config dir))) :command) "project"))))

(ert-deftest pai-mcp-sources-opencode-nearest-git-config-and-repoint ()
  (pai-mcp-sources-test--isolated
    (let ((root (expand-file-name "work" home)))
      (make-directory (expand-file-name ".git" root))
      (pai-mcp-sources-test--file (car (pai-mcp--host-paths "opencode" dir))
                                '(:mcp (:remote (:type "remote" :url "https://old.test" :headers (:Authorization "secret") :oauth (:clientSecret "secret"))
                                               :local (:type "local" :command ("old") :environment (:SECRET "secret")))))
      (pai-mcp-sources-test--file (expand-file-name "opencode.json" root)
                                '(:mcp (:remote (:url "https://new.test") :local (:command ("new")))))
      (let ((servers (plist-get (pai-mcp--load-host "opencode" dir) :servers)))
        (should (equal (plist-get (cdr (assoc "remote" servers)) :url) "https://new.test"))
        (should-not (plist-get (cdr (assoc "remote" servers)) :headers))
        (should-not (plist-get (cdr (assoc "remote" servers)) :oauth))
        (should-not (plist-get (cdr (assoc "local" servers)) :env))))))

(ert-deftest pai-mcp-sources-codex-toml-maps-auth-and-rejects-ambiguity ()
  (pai-mcp-sources-test--isolated
    (let ((file (car (pai-mcp--host-paths "codex" dir))))
      (pai-mcp-sources-test--file file "[mcp_servers.\"remote.name\"]\nurl = 'https://mcp.test/'\nbearer_token_env_var = 'TOKEN'\nhttp_headers = { X-Fixed = 'literal' }\n[mcp_servers.\"remote.name\".env_http_headers]\nX-Env = 'EXTRA'\n[mcp_servers.local]\ncommand = 'tool'\nargs = [\n  'one', # comment\n  \"two\",\n]\n")
      (let* ((servers (plist-get (pai-mcp--load-host "codex" dir) :servers)) (remote (cdr (assoc "remote.name" servers))))
        (should (equal (plist-get remote :bearerTokenEnv) "TOKEN"))
        (should (equal (plist-get (plist-get remote :headers) :X-Env) "$env:EXTRA"))
        (should (equal (plist-get (cdr (assoc "local" servers)) :args) '("one" "two"))))
      (pai-mcp-sources-test--file file "[mcp_servers.x]\ncommand='one'\ncommand='two'\n")
      (should-error (pai-mcp--read-toml-file file))
      (pai-mcp-sources-test--file file "[[mcp_servers.x]]\ncommand='one'\n")
      (should-error (pai-mcp--read-toml-file file)))))

(ert-deftest pai-mcp-sources-jsonc-preserves-quoted-comments ()
  (should (equal (pai-json-decode (pai-mcp--jsonc "{\"url\":\"https://host/*path*/\",/* comment */\"args\":[\"//x\", // trailing\n],}"))
                 '(:url "https://host/*path*/" :args ("//x")))))

(ert-deftest pai-mcp-sources-transport-replacement-strips-credentials ()
  (let ((original '(:url "https://old" :headers (:Authorization "secret") :bearerToken "secret" :oauth (:clientSecret "secret") :timeout 9)))
    (let ((changed (pai-mcp--merge-definition original '(:url "https://new"))))
      (should-not (plist-get changed :headers)) (should-not (plist-get changed :bearerToken)) (should-not (plist-get changed :oauth))
      (should (= 9 (plist-get changed :timeout))))
    (let ((stdio (pai-mcp--merge-definition original '(:command "local"))))
      (should-not (plist-get stdio :url)) (should-not (plist-get stdio :headers)))))

(ert-deftest pai-mcp-sources-package-and-plugin-precedence-and-containment ()
  (pai-mcp-sources-test--isolated
    (let ((package (expand-file-name "pkg" dir)) (agent (expand-file-name "agent" dir)) (claude (expand-file-name "claude" dir)))
      (pai-mcp-sources-test--file (expand-file-name ".pi/settings.json" dir) (list :packages (list package)))
      (pai-mcp-sources-test--file (expand-file-name "package.json" package) '(:name "demo" :pi (:mcp ("mcp.json" "../escape.json"))))
      (pai-mcp-sources-test--file (expand-file-name "mcp.json" package) '(:mcpServers (:srv (:command "package" :env (:LEAK "no")) :only (:command "package-only"))))
      (pai-mcp-sources-test--file (expand-file-name "escape.json" dir) '(:mcpServers (:escape (:command "never"))))
      (pai-mcp-sources-test--file (expand-file-name "plugin.json" agent) '(:$schema "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json" :name "demo"))
      (pai-mcp-sources-test--file (expand-file-name "mcp.json" agent)
                                '(:$schema "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json" :mcpServers (:srv (:type "stdio" :command "agent" :args ("${PLUGIN_ROOT}/run" "$UNEXPANDED") :env (:LITERAL "${NOT_EXPANDED}")))))
      (pai-mcp-sources-test--file (expand-file-name ".mcp.json" claude) '(:mcpServers (:claude (:command "${CLAUDE_PLUGIN_ROOT}/run") :shared (:command "claude"))))
      (pai-mcp-sources-test--file (expand-file-name ".mcp.json" dir)
                                (list :settings (list :agentPluginPaths (list agent)) :claudePlugins (list (list :path claude :mcp t)) :mcpServers '(:shared (:command "project"))))
      (let* ((config (pai-mcp-load-config dir)) (def (cdr (assoc "demo__srv" config))))
        (should (equal (plist-get def :command) "agent"))
        (should-not (plist-get (plist-get def :env) :LEAK))
        (should (equal (car (plist-get def :args)) (expand-file-name "run" agent)))
        (should (member "LITERAL=${NOT_EXPANDED}" (pai-mcp--process-env def)))
        (should (assoc "demo__only" config))
        (should-not (assoc "demo__escape" config))
        (should (equal (plist-get (cdr (assoc "shared" config)) :command) "project"))
        (should (equal (plist-get (cdr (assoc "claude" config)) :command) (expand-file-name "run" claude)))))))

(ert-deftest pai-mcp-sources-agent-plugin-rejects-path-and-header-escapes ()
  (pai-mcp-sources-test--isolated
    (should-error (pai-mcp--agent-plugin-definition '(:type "stdio" :command "../escape") dir "demo"))
    (should-error (pai-mcp--agent-plugin-definition '(:type "stdio" :command "tool" :cwd "${PLUGIN_ROOT}/../escape") dir "demo"))
    (should-error (pai-mcp--agent-plugin-definition '(:type "sse" :url "http://remote.test" ) dir "demo"))
    (should-error (pai-mcp--agent-plugin-definition '(:type "streamable-http" :url "https://remote.test" :headers (:X "a" :x "b")) dir "demo"))))

(ert-deftest pai-mcp-sources-runtime-disposal-snapshots-and-lazy-read ()
  (pai-mcp-sources-test--isolated
    (pai-mcp-sources-test--file (expand-file-name ".mcp.json" dir) '(:mcpServers (:runtime (:command "file"))))
    (let* ((old (pai-mcp-register-server "runtime" '(:command "old") "a"))
           (new (pai-mcp-register-server "runtime" '(:command "new") "b")))
      (funcall (plist-get old :dispose))
      (should (equal (plist-get (cdr (assoc "runtime" (pai-mcp-load-config dir))) :command) "new"))
      (should (equal (plist-get (plist-get (pai-mcp-runtime-snapshot "runtime") :definition) :command) "new"))
      (should-not (pai-mcp-unregister-server "runtime" "a"))
      (let ((status (pai-mcp-status-snapshot dir)))
        (should (equal (plist-get (aref (plist-get status :servers) 0) :status) "not-connected"))
        (should (= 0 (hash-table-count pai-mcp--servers))))
      (funcall (plist-get new :dispose))
      (should (equal (plist-get (cdr (assoc "runtime" (pai-mcp-load-config dir))) :command) "file"))
      (should-error (pai-mcp-runtime-snapshot "runtime")))))

(provide 'pai-mcp-sources-test)
;;; pai-mcp-sources-test.el ends here
